apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret

type: Opaque
data:
  root_password: cm9vdDEyMw==    # root123
  username: cGFydGg=            # parth
  password: cGFydGgxMjM=        # parth123

